TrajectoryPlannerROS:
  max_vel_x: 8
  min_vel_x: 4
  max_vel_theta: 6
  min_vel_theta: -6
  min_in_place_vel_theta: 4

  # tolerance
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

  acc_lim_theta: 6.4
  acc_lim_x: 5
  acc_lim_y: 5

  holonomic_robot: false

  sim_time: 10
  sim_granularity: 0.025
  vx_samples: 10
  vtheta_samples: 20
  meter_scoring: true