obstacle_range: 0.3
raytrace_range: 3.0
footprint: [[0.15, 0.12], [0.15, -0.12],[-0.15, 0.12], [-0.15, -0.12]]
#robot_radius: ir_of_robot
inflation_radius: 0.55
cost_scaling_factor: 3.0

map_type: costmap
map_topic: map
subscribe_to_updates: true

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: /asado/laser/scan, marking: true, clearing: true}