obstacle_range: 0.15
raytrace_range: 3.0
footprint: [[0.15, 0.12], [0.15, -0.12],[-0.15, 0.12], [-0.15, -0.12]]
#robot_radius: ir_of_robot
inflation_radius: 0.55

map_topic: map
subscribe_to_updates: true

observation_sources: point_cloud_sensor

point_cloud_sensor: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: /asado/laser/scan, marking: true, clearing: true}