shutdown_costmaps: false
controller_frequency: 2
controller_patience: 2.0
planner_frequency: 2.0
planner_patience: 5.0
oscillation_timeout: 10
oscillation_distance: 0.2

# recovery_behaviors:
#   - name: 'conservative_reset'
#     type: 'clear_costmap_recovery/ClearCostmapRecovery'
  # - name: 'aggressive_reset'
  #   type: 'clear_costmap_recovery/ClearCostmapRecovery'
# conservative_reset:
#   reset_distance: 3.0
#   layer_names: 
#      - obstacles
    
# aggressive_reset:
#   reset_distance: 0.0
#   layer_names:
#      - obstacles  

